export const quotes: string[] = [
  "The only way to do great work is to love what you do. - Steve Jobs",
  "The best way to predict the future is to invent it. - Alan Kay",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "The purpose of our lives is to be happy. - Dalai Lama",
  "Life is what happens when you're busy making other plans. - John Lennon",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "It always seems impossible until it's done. - Nelson Mandela",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
  "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "The best revenge is massive success. - Frank Sinatra",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
  "Your life does not get better by chance, it gets better by change. - Jim Rohn",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "Go confidently in the direction of your dreams. Live the life you have imagined. - Henry David Thoreau",
  "With the new day comes new strength and new thoughts. - Eleanor Roosevelt",
  "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty. - Winston Churchill",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
  "Act as if what you do makes a difference. It does. - William James",
  "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
  "Don't let yesterday take up too much of today. - Will Rogers",
  "You are never too small to make a difference. - Greta Thunberg",
  "The harder you work for something, the greater you'll feel when you achieve it. - Unknown",
  "Dream big and dare to fail. - Norman Vaughan",
  "The journey of a thousand miles begins with a single step. - Lao Tzu",
  "It is never too late to be what you might have been. - George Eliot",
  "If you want to live a happy life, tie it to a goal, not to people or things. - Albert Einstein",
  "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. - Buddha",
  "The secret of getting ahead is getting started. - Mark Twain",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
  "Happiness is not something readymade. It comes from your own actions. - Dalai Lama",
  "You must do the things you think you cannot do. - Eleanor Roosevelt",
  "The most common way people give up their power is by thinking they don't have any. - Alice Walker",
  "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
  "Change your thoughts and you change your world. - Norman Vincent Peale",
  "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
  "Either write something worth reading or do something worth writing. - Benjamin Franklin",
  "You miss 100% of the shots you don't take. - Wayne Gretzky",
  "The key to success is to focus on goals, not obstacles. - Unknown",
  "A person who never made a mistake never tried anything new. - Albert Einstein",
  "Happiness is when what you think, what you say, and what you do are in harmony. - Mahatma Gandhi",
  "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
  "Do not wait to strike till the iron is hot; but make it hot by striking. - William Butler Yeats",
  "The future starts today, not tomorrow. - Pope John Paul II",
  "You can't use up creativity. The more you use, the more you have. - Maya Angelou",
  "The way get started is to quit talking and begin doing. - Walt Disney",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "Very often, a change of self is needed more than a change of scene. - Arthur Christopher Benson",
  "The only true wisdom is in knowing you know nothing. - Socrates",
  "To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde",
  "You must be the change you wish to see in the world. - Mahatma Gandhi",
  "The best preparation for tomorrow is doing your best today. - H. Jackson Brown Jr.",
  "It is during our darkest moments that we must focus to see the light. - Aristotle",
  "The roots of education are bitter, but the fruit is sweet. - Aristotle",
  "If you tell the truth, you don't have to remember anything. - Mark Twain",
  "The only impossible journey is the one you never begin. - Tony Robbins",
  "You can't build a reputation on what you are going to do. - Henry Ford",
  "The most courageous act is still to think for yourself. Aloud. - Coco Chanel",
  "If opportunity doesn't knock, build a door. - Milton Berle",
  "The greatest weapon against stress is our ability to choose one thought over another. - William James",
  "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
  "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
  "The question isn't who is going to let me; it's who is going to stop me. - Ayn Rand",
  "Do not let what you cannot do interfere with what you can do. - John Wooden",
  "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
  "It's not the years in your life that count. It's the life in your years. - Abraham Lincoln",
  "The power of imagination makes us infinite. - John Muir",
  "Sometimes the questions are complicated and the answers are simple. - Dr. Seuss",
  "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. - Dr. Seuss",
  "Everything you've ever wanted is on the other side of fear. - George Addair",
  "The best time to start was yesterday. The next best time is now. - Unknown",
  "If you can dream it, you can achieve it. - Zig Ziglar",
  "You are what you repeatedly do. Excellence, then, is not an act, but a habit. - Aristotle",
];

export function getRandomQuote(): string {
  return quotes[Math.floor(Math.random() * quotes.length)];
}
